import { CourseMiniCardType } from "@/components/molecules/CourseMiniCard";
import { CourseBigCardType } from "@/components/molecules/CourseBigCard";

export const COURSE_MINI_CARD_CONTENT: CourseMiniCardType[] = [
  {
    title: "UX Design Fundamentals: Navigating User Journeys",
    imageUrl: "/courses/course1.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Wireframe Mastery: Crafting Intuitive Interfaces",
    imageUrl: "/courses/course2.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Wireframe Wizardry: Designing User-Centric Blueprints",
    imageUrl: "/courses/course3.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Web & Mobile Development: Coding for Exceptional User Experiences",
    imageUrl: "/courses/course4.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Web & Mobile Development: Building Interactive Experiences",
    imageUrl: "/courses/course5.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "The Art of UX Research: Uncover User Insights",
    imageUrl: "/courses/course6.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Wireframe Mastery: Crafting Intuitive Interfaces",
    imageUrl: "/courses/course2.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Wireframe Wizardry: Designing User-Centric Blueprints",
    imageUrl: "/courses/course3.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "UX Design Fundamentals: Navigating User Journeys",
    imageUrl: "/courses/course1.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
];

export const COURSE_BIG_CARD_CONTENT: CourseBigCardType[] = [
  {
    title: "UX Fundamental 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course1.png",
  },
  {
    title: "UX Fundamental 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course2.png",
  },
  {
    title: "UX Fundamental 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course3.png",
  },
  {
    title: "Javascript Fundamental 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course4.png",
  },
  {
    title: "HTML Course 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course5.png",
  },
];
