import { CourseMiniCardType } from "@/components/molecules/CourseMiniCard";

export const COURSE_MINI_CARD_CONTENT: CourseMiniCardType[] = [
  {
    title: "UX Design Fundamentals: Navigating User Journeys",
    imageUrl: "/courses/course1.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
  {
    title: "Wireframe Mastery: Crafting Intuitive Interfaces",
    imageUrl: "/courses/course2.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
  {
    title: "Wireframe Wizardry: Designing User-Centric Blueprints",
    imageUrl: "/courses/course3.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
  {
    title: "Web & Mobile Development: Coding for Exceptional User Experiences",
    imageUrl: "/courses/course4.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
  {
    title: "Web & Mobile Development: Building Interactive Experiences",
    imageUrl: "/courses/course5.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
  {
    title: "The Art of UX Research: Uncover User Insights",
    imageUrl: "/courses/course6.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
  {
    title: "Wireframe Mastery: Crafting Intuitive Interfaces",
    imageUrl: "/courses/course2.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
  {
    title: "Wireframe Wizardry: Designing User-Centric Blueprints",
    imageUrl: "/courses/course3.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
  {
    title: "UX Design Fundamentals: Navigating User Journeys",
    imageUrl: "/courses/course1.png",
    totalReview: 3400,
    discountPrice: 429000,
    price: 129000,
    star: 4,
  },
];
