import { CourseMiniCardType } from "@/components/molecules/CourseMiniCard";
import { CourseBigCardType } from "@/components/molecules/CourseBigCard";
import { MyCourseItemType } from "@/components/molecules/MyCourseItem";

export const COURSE_MINI_CARD_CONTENT: CourseMiniCardType[] = [
  {
    title: "UX Design Fundamentals: Navigating User Journeys",
    imageUrl: "/courses/course1.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Wireframe Mastery: Crafting Intuitive Interfaces",
    imageUrl: "/courses/course2.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Wireframe Wizardry: Designing User-Centric Blueprints",
    imageUrl: "/courses/course3.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Web & Mobile Development: Coding for Exceptional User Experiences",
    imageUrl: "/courses/course4.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Web & Mobile Development: Building Interactive Experiences",
    imageUrl: "/courses/course5.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "The Art of UX Research: Uncover User Insights",
    imageUrl: "/courses/course6.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Wireframe Mastery: Crafting Intuitive Interfaces",
    imageUrl: "/courses/course2.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "Wireframe Wizardry: Designing User-Centric Blueprints",
    imageUrl: "/courses/course3.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
  {
    title: "UX Design Fundamentals: Navigating User Journeys",
    imageUrl: "/courses/course1.png",
    reviewCount: 3400,
    discountPrice: 429000,
    price: 129000,
    rating: 4,
  },
];

export const COURSE_BIG_CARD_CONTENT: CourseBigCardType[] = [
  {
    title: "UX Fundamental 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course1.png",
  },
  {
    title: "UX Fundamental 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course2.png",
  },
  {
    title: "UX Fundamental 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course3.png",
  },
  {
    title: "Javascript Fundamental 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course4.png",
  },
  {
    title: "HTML Course 101",
    rating: 4.78,
    reviewCount: 3200,
    duration: 29880000,
    price: 150000,
    imageUrl: "/courses/course5.png",
  },
];

export const MY_COURSE_OVERVIEWS: MyCourseItemType[] = [
  {
    title: "UX Fundamental 101",
    progress: 0,
    last_chapter: null,
    points: null,
    isStarted: false,
    isFinished: false,
    imageUrl: "/courses/course1.png",
  },
  {
    title: "UX Research Fundamental",
    progress: 0,
    last_chapter: "Chapter 3 : How to create UX Report",
    points: "500/1000",
    isStarted: true,
    isFinished: false,
    imageUrl: "/courses/course2.png",
  },
  {
    title: "UI Fundamental 101",
    progress: 0,
    last_chapter: "",
    points: "1000",
    isStarted: true,
    isFinished: true,
    imageUrl: "/courses/course3.png",
  },
];

export const MY_COURSES: MyCourseItemType[] = [
  {
    title: "UX Writing for Beginner",
    progress: 50,
    last_chapter: "Chapter 2 : Fundamental User Interface",
    points: "500/1000",
    isStarted: true,
    isFinished: false,
    imageUrl: "/courses/course1.png",
    isBordered: true,
  },
  {
    title: "UX Research Methods",
    progress: 50,
    last_chapter: "Chapter 3 : How to choose the right methods",
    points: "500/1000",
    isStarted: true,
    isFinished: false,
    imageUrl: "/courses/course2.png",
    isBordered: true,
  },
  {
    title: "Portfolio for UX Writing",
    progress: 100,
    last_chapter: "Chapter 3 : How to choose the right methods",
    points: "1000/1000",
    isStarted: true,
    isFinished: true,
    imageUrl: "/courses/course3.png",
    isBordered: true,
  },
  {
    title: "Portfolio for UX Writing",
    progress: 100,
    last_chapter: "Chapter 3 : How to choose the right methods",
    points: "1000/1000",
    isStarted: true,
    isFinished: true,
    imageUrl: "/courses/course4.png",
    isBordered: true,
  },
  {
    title: "Portfolio for UX Writing",
    progress: 100,
    last_chapter: "Chapter 3 : How to choose the right methods",
    points: "1000/1000",
    isStarted: true,
    isFinished: true,
    imageUrl: "/courses/course5.png",
    isBordered: true,
  },
];
